// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateProvider(arg1) {
  return window['go']['backend']['App']['ActivateProvider'](arg1);
}

export function Bootstrap() {
  return window['go']['backend']['App']['Bootstrap']();
}

export function ClearArchivedSessions() {
  return window['go']['backend']['App']['ClearArchivedSessions']();
}

export function DeleteProvider(arg1) {
  return window['go']['backend']['App']['DeleteProvider'](arg1);
}

export function GetInstallationStatus() {
  return window['go']['backend']['App']['GetInstallationStatus']();
}

export function GetProviders() {
  return window['go']['backend']['App']['GetProviders']();
}

export function GetSettings() {
  return window['go']['backend']['App']['GetSettings']();
}

export function ListArchivedSessions() {
  return window['go']['backend']['App']['ListArchivedSessions']();
}

export function RemoveArchivedSession(arg1) {
  return window['go']['backend']['App']['RemoveArchivedSession'](arg1);
}

export function RestoreArchivedSession(arg1) {
  return window['go']['backend']['App']['RestoreArchivedSession'](arg1);
}

export function SaveProvider(arg1) {
  return window['go']['backend']['App']['SaveProvider'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['backend']['App']['SaveSettings'](arg1);
}
