// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function ActivateProvider(arg1:string):Promise<backend.ProviderResult>;

export function Bootstrap():Promise<backend.BootstrapState>;

export function ClearArchivedSessions():Promise<backend.ActionResult>;

export function DeleteProvider(arg1:string):Promise<backend.ProviderResult>;

export function GetInstallationStatus():Promise<backend.InstallationStatus>;

export function GetProviders():Promise<backend.ProviderState>;

export function GetSettings():Promise<backend.AppSettings>;

export function ListArchivedSessions():Promise<Array<backend.Session>>;

export function RemoveArchivedSession(arg1:string):Promise<backend.ActionResult>;

export function RestoreArchivedSession(arg1:string):Promise<backend.ActionResult>;

export function SaveProvider(arg1:backend.ProviderInput):Promise<backend.ProviderResult>;

export function SaveSettings(arg1:backend.AppSettings):Promise<backend.AppSettings>;
